General:
  ListenAddress: 127.0.0.1
  ListenPort: 7052
  TLS:
    Enabled: true
    PrivateKey: ./tls/keystore/private_key_sk ## replace with first private key file name in tls/keystore
    Certificate: ./tls/signcerts/fullchain.pem
    RootCAs:
      - ./tls/tlscacerts/tls-localhost-7054.pem
  Cluster:
    ListenAddress: 0.0.0.0
    ListenPort: 8052
    ClientCertificate: ./tls/signcerts/fullchain.pem
    ClientPrivateKey: ./tls/keystore/private_key_sk ## replace with first private key file name in tls/keystore
    ServerCertificate: ./tls/signcerts/fullchain.pem
    ServerPrivateKey: ./tls/keystore/private_key_sk ## replace with first private key file name in tls/keystore
    RootCAs:
      - ./tls/tlscacerts/tls-localhost-7054.pem
  LocalMSPDir: ./msp
  LocalMSPID: Org1MSP
  BootstrapMethod: file
  BootstrapFile: genesisblock

FileLedger:
  Location: /var/hyperledger/production/orderer3

Operations:
  ListenAddress: 127.0.0.1:8445

Consensus:
  WALDir: /var/hyperledger/production/orderer3/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer3/etcdraft/snapshot