version: '2'

services:
  couchdb:
    container_name: couchdb
    image: couchdb:3.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
    networks:
      - fabric_network

  peer0.org1.example.com:
    hostname: peer0.org1.example.com
    image: hyperledger/fabric-peer:2.4.7
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7071
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7071
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7061
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/peer/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/peer/tls/keystore/private_key_sk
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/peer/tls/tlscacerts/tls-localhost-7054.pem
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
    volumes:
      - /var/run/:/host/var/run/
      - ./peer0.org1.example.com/msp:/var/hyperledger/peer/msp
      - ./peer0.org1.example.com/tls:/var/hyperledger/peer/tls
      - ./peer0.org1.example.com/data:/var/hyperledger/production
    ports:
      - 7061:7061
      - 7071:7071
    networks:
      - fabric_network

networks:
  fabric_network:
    external: true